enum Category {
  'Array',
  'String',
  'Algorithms',
  'Linked List',
  'Tree',
  'Graph',
  'Dynamic Programming',
  'Backtracking',
  'Math',
  'Hash Table',
  'Stack',
  'Queue',
  'Heap',
  'Sort',
  'Binary Search',
  'Greedy',
  'Bit Manipulation',
  'Divide and Conquer',
  'Design',
  'Topological Sort',
  'Data Structures',
  'Sliding Window',
  'Recursion',
  'Two Pointers',
  'Trie',
  'Sorting',
  "Heap (Priority Queue)",
  "Merge Sort",
  "String Matching"
}

export default Category;
