import { QuestionString } from "../Commons"

class QuestionValidator {
  // check for empty fields
  public validateEmptyFields(input: QuestionString) {
    if (!input.title) {
      throw new Error('Title cannot be empty')
    }
    if (!input.categories) {
      throw new Error('Categories cannot be empty')
    }
    if (!input.complexity) {
      throw new Error('Complexity cannot be empty')
    }
    if (!input.link) {
      throw new Error('Link cannot be empty')
    }
    if (!input.description) {
      throw new Error('Description cannot be empty')
    }
    return true;
  }

  // Temporary implementation for assignment 1 ------------------------------------------
  // We only check duplicate titles, as ID is automatically generated by the backend.
  public validateDuplicateQuestions(input: QuestionString, qnList: QuestionString[]) {
    qnList.forEach((qn) => {
      if (qn.title === input.title) {
        throw new Error('Duplicate question title');
      }
    })
  }
  // -------------------------------------------------------------------------------------------
}

export default QuestionValidator;